version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flightservice_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    container_name: flightservice_redis
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Stack Web UI
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    restart: unless-stopped

